# See doc/docker/README.md or https://github.com/instructure/canvas-lms/tree/master/doc/docker
version: '2'
services:
  web: &WEB
    build:
      context: .
    links:
      - postgres
      - redis
    environment:
      POSTGRES_PASSWORD: sekret
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  jobs:
    <<: *WEB
    command: bundle exec script/delayed_job run
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    build: ./docker-compose/postgres
    environment:
      POSTGRES_PASSWORD: sekret
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:alpine
    logging:
      options:
        max-size: "10m"
        max-file: "3"
